### ISSUE TITLE
Replace pdfmerger due to Java 6 dependency

### ISSUE THREAD

**Issue by mLuby** [mLuby/images-to-pdf#1]
- [ ] Replace [pdfmerger](https://www.npmjs.com/package/pdfmerger) with something without system-specific dependencies.
- [ ] remove [Dependencies section](https://github.com/mLuby/images-to-pdf#dependencies) of README

**Comment by bompi88** [comment]
I'm not 100% sure, but you could probably use https://github.com/galkahana/HummusJS? See here: https://github.com/galkahana/HummusJS/blob/b699d6a01ba027428120cbe5b1c16813bed0521d/src/DocumentCopyingContextDriver.cpp#L212

**Comment by mLuby** [comment]
Thanks! Hummus has a CPP dependency but I think that's much better supported than Java.
