### ISSUE TITLE
 Unexpected token function

### ISSUE THREAD

**Issue by haris-crewlogix** [mLuby/images-to-pdf#8]
When I import the package it gives an error.

```js
async function imagesToPdf (paths, resultPath) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/user_code/APIs/GetSignedDocument/getSignedDocument.js:25:21)


Functions deploy had errors. To continue deploying other features (such as database), run:
    firebase deploy --except functions
```

**Comment by mLuby** [comment]
Pretty sure that's to do with your environment not supporting `async` functions. They became available in `$ node -v 7.6.0`. Or you can run your code through a transpiler like Babel.

In your environment, are you able to test this function? 
```js
async function testAsync () { console.log("async supported"); };
testAsync();
```

**Comment by haris-crewlogix** [comment]
Yes,async functions are supported. I have tested this function, below is the attached screen shot. 

![Console sc](https://user-images.githubusercontent.com/48751184/55053215-4d541180-507d-11e9-8912-518fdfc0cf92.png)

**Comment by mLuby** [comment]
Hmm, this could be tricky to debug. Could you please create a new repo, install the package, and try a test? Here are the instructions just so we're doing the same things:
```sh
mkdir testproject
cd testproject
npm install images-to-pdf
node
```
```js
const imagesToPdf = require("images-to-pdf")
imagesToPdf(["node_modules/images-to-pdf/test/images/1.jpeg", "node_modules/images-to-pdf/test/images/3.png"], "combined.pdf").then(console.log).catch(console.error)
.exit
```
```sh
open combined.pdf
```
At this point, I see [combined.pdf](https://github.com/mLuby/images-to-pdf/files/3014615/combined.pdf) contains images of a red 1 and a gold 3. Is that what you see?

**Comment by mLuby** [comment]
Closing due to no response.
