### ISSUE TITLE
Print PDF from IMG with EXIF data

### ISSUE THREAD

**Issue by qubiack** [mLuby/images-to-pdf#9]
It's possible to print PDF with specified DPI? 

For example, I have a .jpeg file with 5906x8268px and I set 300DPI in EXIF data, but when I print this to PDF I have only 72DPI and size instead of 50x70cm is now 208,4x291,7cm.

**Comment by mLuby** [comment]
I doubt it. This is just a [thin wrapper](https://github.com/mLuby/images-to-pdf/blob/master/imagesToPdf.js#L10-L17) for Hummus, so that's where you might try customizing.
